# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Khaos::ShopList"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
#template: "simple"

template: "template_toolkit"
engines:
    template:
        template_toolkit:
#            start_tag: '<%'
#            end_tag:   '%>'
#            WRAPPER: layouts/main.tt

plugins:
    Database:
        driver: Pg
        database: 'shoplist'
        host: 'localhost'
        port: 5432
        sslmode : 'require'
        username: 'shoplist_write'
        password: 'password'
        connection_check_threshold: 10
        dbi_params:
            sslmode: 'require'
            RaiseError: 1
            AutoCommit: 1

